# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a8d12a24be3722403665731e3a19e671c7944bd7e659878032fd618521316c661b95cfb9b097728c618d98d934ba4a76c52ca1912ec5e75bb3830a4200e070b

test:
  secret_key_base: 167720792ecdec51738497bcca434bde350c1fe47a33bdfb2913a3ce8226ec8b51e97aa10c87bf50b797ce5a87c5b6dd2144ba47660d9b1787a8d30628f3a338

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
