class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase) 
      # the params hash generated by the signin form has the email/password hash inside it
    if user && user.authenticate(params[:session][:password]) 
      # checks that user exists and can be authenticated through the secure_passwords method
      sign_in user # Note: We have to write "sign_in" function ourselves
      redirect_to user # How does Rails know this represents a web page?
    else
      flash.now[:error] = 'Wrong email and password'
        # flash.now works for rendered pages, vanishes when users go elsewhere
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end
